//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Id3.Files.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FileNamerMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FileNamerMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Id3.Files.Resources.FileNamerMessages", typeof(FileNamerMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more null or empty patterns were found..
        /// </summary>
        internal static string FoundNullOrEmptyPatterns {
            get {
                return ResourceManager.GetString("FoundNullOrEmptyPatterns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file path.
        /// </summary>
        internal static string InvalidFilePath {
            get {
                return ResourceManager.GetString("InvalidFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing data for &apos;{0}&apos;.
        /// </summary>
        internal static string MissingDataForFrame {
            get {
                return ResourceManager.GetString("MissingDataForFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory &apos;{0}&apos; does not exist.
        /// </summary>
        internal static string MissingDirectory {
            get {
                return ResourceManager.GetString("MissingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does not exist.
        /// </summary>
        internal static string MissingFile {
            get {
                return ResourceManager.GetString("MissingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does not contain a ID3v2.3 tag.
        /// </summary>
        internal static string MissingId3v23TagInFile {
            get {
                return ResourceManager.GetString("MissingId3v23TagInFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No patterns have been specified. Specify at least one pattern..
        /// </summary>
        internal static string MissingPatterns {
            get {
                return ResourceManager.GetString("MissingPatterns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The naming pattern &apos;{0}&apos; does not contain any placeholders.
        /// </summary>
        internal static string MissingPlaceholdersInPattern {
            get {
                return ResourceManager.GetString("MissingPlaceholdersInPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A tag property by name &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string MissingTagProperty {
            get {
                return ResourceManager.GetString("MissingTagProperty", resourceCulture);
            }
        }
    }
}
